//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYCourseSelection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.SelectCourse = new HashSet<SelectCourse>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string CourseInfo { get; set; }
        public System.DateTime ClassStartTime { get; set; }
        public string CourseAddress { get; set; }
        public int CourseCredit { get; set; }
        public System.DateTime CourseStartTime { get; set; }
        public System.DateTime CourseEndTime { get; set; }
        public int CourseSumPeople { get; set; }
        public int CourseNumPeople { get; set; }
        public int CourseState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectCourse> SelectCourse { get; set; }
    }
}
