//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYCourseSelection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tea_Grade
    {
        public int Tea_GradeID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
