//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYCourseSelection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZYCourseSelectionEntities : DbContext
    {
        public ZYCourseSelectionEntities()
            : base("name=ZYCourseSelectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Major> Major { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<SelectCourse> SelectCourse { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Tea_Grade> Tea_Grade { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
